{
 "title": "Zookeeper",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Zookeeper - CPU Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"zookeeper-jmx\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Zookeeper - Resident Memory Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"zookeeper-jmx\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Zookeeper - JVM Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"zookeeper-jmx\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Zookeeper - JVM Committed Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{job=\"zookeeper-jmx\"}",
     "legendFormat": "{{instance}}-{{area}}"
    }
   ]
  },
  {
   "title": "Zookeeper - Packets Received/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(zookeeper_packetsreceived[5m])",
     "legendFormat": "ReplicaID={{replicaId}}"
    }
   ]
  },
  {
   "title": "Zookeeper - Packets Sent/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(zookeeper_packetssent[5m])",
     "legendFormat": "ReplicaID={{replicaId}}"
    }
   ]
  },
  {
   "title": "Zookeeper - Avg Request Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "zookeeper_avgrequestlatency", "legendFormat": "ReplicaID={{replicaId}}" }
   ]
  },
  {
   "title": "Zookeeper - Num Alive Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "zookeeper_numaliveconnections", "legendFormat": "ReplicaID={{replicaId}}" }
   ]
  }
 ]
}