{
 "title": "Kafka",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Kafka - CPU Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka-jmx\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Kafka - Resident Memory Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"kafka-jmx\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Kafka - JVM Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"kafka-jmx\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kafka - JVM Committed Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{job=\"kafka-jmx\"}",
     "legendFormat": "{{instance}}-{{area}}"
    }
   ]
  },
  {
   "title": "Kafka - Total Fetch Requests/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_totalfetchrequests_total{topic!=\"\"}[5m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka - Total Produce Requests/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_totalproducerequests_total{topic!=\"\"}[5m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka - Requests Total Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_totaltimems{quantile='0.95', request=~\"Fetch|FetchConsumer|Produce|Metadata\"}",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Kafka - Purgatory Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_server_delayedoperationpurgatory_purgatorysize{delayedOperation=~\"Fetch|FetchConsumer|Produce|Metadata\"}",
     "legendFormat": "{{delayedOperation}}"
    }
   ]
  },
  {
   "title": "Kafka - Active Controller Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kafka - Under Replicated Partitions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_underreplicatedpartitions",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}